#!/usr/bin/env python3
"""Step 18 automated browser/runtime production gate.

Consumes features and pitch generated by the browser-compatible JS front end.
Evaluates the whole Stage-A -> physical mask -> temporal Stage-B cycle with
leave-one-entire-MIDI-out validation. Smoke uses the full extracted training
pool but scores a small representative eval subset; real scores all 384.
"""
import argparse,json,time
from pathlib import Path
import numpy as np,pandas as pd
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier
OPEN={1:27,2:34,3:39,4:44,5:49,6:54,7:58,8:63}

def clf(n,k):
 return XGBClassifier(n_estimators=n,max_depth=3,learning_rate=.04,subsample=.85,colsample_bytree=.85,reg_lambda=2,objective="multi:softprob",num_class=k,random_state=42,n_jobs=8)
def mask(p,m):
 q=p.copy()
 for i,s in enumerate(range(1,9)):
  if not OPEN[s]<=m<=OPEN[s]+24:q[i]=0
 z=q.sum();return q/z if z else q
def main():
 ap=argparse.ArgumentParser();ap.add_argument("browser_json",type=Path);ap.add_argument("--out",type=Path,required=True);ap.add_argument("--smoke",action="store_true");a=ap.parse_args();a.out.mkdir(parents=True,exist_ok=True)
 rows=json.loads(a.browser_json.read_text());df=pd.DataFrame([{k:v for k,v in r.items() if k!="features"} for r in rows])
 X=[np.asarray([r["features"][j] for r in rows],np.float32) for j in range(3)]
 truth=df.string.to_numpy(int);mids=df.true_midi.to_numpy(int);pm=df.pred_midi.fillna(-999).to_numpy(int)
 evalmask=np.ones(len(df),bool)
 if a.smoke:evalmask=(mids>=54)&(mids<=60)&(df.strength.to_numpy()=="normal")
 P=[np.zeros((len(df),8)) for _ in range(3)];trees=20 if a.smoke else 100;st=time.time()
 for n,m in enumerate(sorted(df.true_midi.unique()),1):
  te=np.where((mids==m)&evalmask)[0]
  if not len(te):continue
  tr=np.where(mids!=m)[0];classes=np.sort(np.unique(truth[tr]));enc={s:i for i,s in enumerate(classes)}
  for j in range(3):
   sc=StandardScaler().fit(X[j][tr]);model=clf(trees,len(classes));model.fit(sc.transform(X[j][tr]),np.array([enc[s] for s in truth[tr]]))
   raw=model.predict_proba(sc.transform(X[j][te]))
   for ci,s in enumerate(classes):P[j][te,s-1]=raw[:,ci]
  e=time.time()-st;print(f"STAGEB FOLD [{n}] MIDI {m} elapsed={e:.1f}s",flush=True)
 idx=np.where(evalmask)[0];pred=[];conf=[]
 for i in idx:
  if pm[i]<0:q=np.mean([P[j][i] for j in range(3)],axis=0)
  else:q=np.mean([mask(P[j][i],pm[i]) for j in range(3)],axis=0)
  pred.append(int(np.argmax(q)+1));conf.append(float(np.max(q)))
 pred=np.array(pred);tm=mids[idx];ts=truth[idx];pp=pm[idx];pitch=pp==tm;string=pred==ts;both=pitch&string
 out=pd.DataFrame({"file":df.file.iloc[idx],"true_midi":tm,"pred_midi":pp,"true_string":ts,"pred_string":pred,"confidence":conf,"pitch_correct":pitch,"string_correct":string,"tuple_correct":both})
 out.to_csv(a.out/"browser_pipeline_predictions.csv",index=False)
 summary={"step":18,"phase":"automated_browser_runtime","smoke":a.smoke,"recordings_scored":len(idx),"browser_frontend":"JS custom YIN 240ms + Meyda MFCC 3x40ms","pitch_correct":int(pitch.sum()),"pitch_accuracy":float(pitch.mean()),"string_correct_all":int(string.sum()),"string_accuracy":float(string.mean()),"string_accuracy_given_correct_pitch":float(string[pitch].mean()) if pitch.any() else 0,"tuple_correct":int(both.sum()),"tuple_accuracy":float(both.mean()),"mean_js_pitch_runtime_ms":float(df.pitch_runtime_ms.iloc[idx].mean()),"mean_js_feature_runtime_ms":float(df.feature_runtime_ms.iloc[idx].mean()),"acceptance":{"pipeline_completed":True,"no_trainer_context":True}}
 (a.out/"summary.json").write_text(json.dumps(summary,indent=2));print(json.dumps(summary,indent=2))
if __name__=="__main__":main()
